version: '3.3'
services:
  web:
    image: silentsnowman/resume-website:${TAG}
    ports:
      - "${PORT}:80"
    depends_on:
      - cycle
      - stock
      - currency
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  cycle:
    image: silentsnowman/cycle-service:${TAG}
    secrets:
      - strava_client_id
      - strava_client_secret
      - strava_refresh_token
    environment:
      - STRAVA_CLIENT_ID_FILE=/run/secrets/strava_client_id
      - STRAVA_CLIENT_SECRET_FILE=/run/secrets/strava_client_secret
      - STRAVA_REFRESH_TOKEN_FILE=/run/secrets/strava_refresh_token
      - YEAR_GOAL=900
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  stock:
    image: silentsnowman/stock-service:${TAG}
    secrets:
      - alpha_vantage_api_key
    environment:
      - ALPHA_VANTAGE_API_KEY_FILE=/run/secrets/alpha_vantage_api_key
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  currency:
    image: silentsnowman/currency-service:${TAG}
    secrets:
      - free_currconv_api_key
    environment:
      - FREE_CURRCONV_API_KEY_FILE=/run/secrets/free_currconv_api_key
      - REDIS_SERVER_AND_PORT=redis:6379
      - REDIS_CACHE_DURATION_IN_MINUTES=60
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  redis:
    image: redis:6.0.9
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "false"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --interval 1800 
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
secrets:
  strava_client_id:
    file: strava_client_id.txt
  strava_client_secret:
    file: strava_client_secret.txt
  strava_refresh_token:
    file: strava_refresh_token.txt
  alpha_vantage_api_key:
    file: alpha_vantage_api_key.txt
  free_currconv_api_key:
    file: free_currconv_api_key.txt
