version: '3.7'
services:
  web:
    image: silentsnowman/resume-website:${TAG}
    ports:
      - "${PORT}:80"
    depends_on:
      - cycle
      - stock
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  cycle:
    image: silentsnowman/cycle-service:${TAG}
    secrets:
      - strava_access_token
    environment:
      - STRAVA_ACCESS_TOKEN_FILE=/run/secrets/strava_access_token
      - YEAR_GOAL=900
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  stock:
    image: silentsnowman/stock-service:${TAG}
    secrets:
      - alpha_vantage_api_key
    environment:
      - ALPHA_VANTAGE_API_KEY_FILE=/run/secrets/alpha_vantage_api_key
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
secrets:
   strava_access_token:
     file: strava_access_token.txt
   alpha_vantage_api_key:
     file: alpha_vantage_api_key.txt
volumes:
  jenkins_home:
