#!/usr/bin/env bash

STAGING_BRANCH=staging
STAGING_DOCKER_PORT=8000
STAGING_DOCKER_TAG=staging
STAGING_DOMAIN_NAME=staging.nathangrubb.io

PROD_BRANCH=master
PROD_DOCKER_PORT=9000
PROD_DOCKER_TAG=latest
PROD_DOMAIN_NAME=nathangrubb.io

